workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.ninotek.ninorent"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android Release & Debug APKs
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease assembleDebug
      - name: Rename Release APK
        script: |
          VERSION_NAME=$(grep 'versionName = ' app/build.gradle.kts | sed 's/.*versionName = "\(.*\)".*/\1/' | head -n 1)
          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            mv app/build/outputs/apk/release/app-release.apk "app/build/outputs/apk/release/NinoRent_ver_${VERSION_NAME}.apk"
          fi
          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            mv app/build/outputs/apk/release/app-release-unsigned.apk "app/build/outputs/apk/release/NinoRent_ver_${VERSION_NAME}-unsigned.apk"
          fi
    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - admin@ninotek.vn
